/**
 * TypeScript backend — IRModule → a single, runnable ES module string.
 *
 * The emitted module exports `createExpert(rt, inputs = {})` matching
 * `ExpertFactory` in ../../runtime/runtime.ts. It walks the language-neutral IR
 * (../../ir/nodes.ts) and emits TypeScript exactly per that file's emission-ABI
 * doc-comment:
 *
 *   - IRRef input/global/local/param          → bare identifier
 *   - IRRef builtinConst | contextVar          → `rt.NAME`
 *   - IRRef enumMember                          → `rt.NAME`
 *   - IRCall intrinsic{name} isAsync            → `(await )rt.name(args)`
 *   - IRCall method{receiver,method} isAsync    → `(await )receiver.method(args)`
 *   - IRCall user{name} isAsync                 → `(await )name(args)`
 *   - IRNew CTrade                              → `new rt.CTrade(rt, ...args)`
 *   - IRFunction isAsync                        → `async function ...`
 *
 * No semantic decisions are made here: async-ness, intrinsic classification,
 * and integer-arithmetic flags all arrive pre-computed on the IR. The emitter
 * is a faithful printer.
 */

import type {
  IRModule,
  IRInput,
  IRGlobal,
  IRFunction,
  IRClass,
  IRMethod,
  IRField,
  IRParam,
  IRStmt,
  IRBlock,
  IRVarDecl,
  IRExprStmt,
  IRIf,
  IRFor,
  IRWhile,
  IRDoWhile,
  IRReturn,
  IRSwitch,
  IRExpr,
  IRNum,
  IRStr,
  IRBool,
  IRRef,
  IRMember,
  IRIndex,
  IRCall,
  IRNew,
  IRDelete,
  IRUnary,
  IRBinary,
  IRAssign,
  IRTernary,
  IRCast,
  IRType,
} from '../../ir/nodes';
import { isStdlibClass } from '../../sema/intrinsics';

// ─────────────────────────────────────────────────────────────────────────
// Public entry point
// ─────────────────────────────────────────────────────────────────────────

/**
 * Emit a complete, runnable TypeScript ES module for `mod`.
 *
 * The result is a single string: a banner, the `createExpert` factory holding
 * the program's inputs / globals / functions, and a `return { ...handlers,
 * __inputs }` object whose keys are the recognised event handlers found in the
 * module's `events` map.
 */
export function emitTypeScript(mod: IRModule): string {
  const e = new Emitter();
  return e.emitModule(mod);
}

// ─────────────────────────────────────────────────────────────────────────
// Emitter
// ─────────────────────────────────────────────────────────────────────────

const INDENT = '  ';

class Emitter {
  private out: string[] = [];
  private depth = 0;
  /**
   * Names of user-declared classes/structs in this module. A `new` of one of
   * these emits a BARE `new Foo(...)` (the class is a top-level decl in the
   * emitted module); a `new` of anything else goes through `rt` (runtime struct
   * / stdlib class). Populated at emitModule entry.
   */
  private userClassNames: ReadonlySet<string> = new Set();

  // ── output helpers ──

  private line(text = ''): void {
    if (text === '') {
      this.out.push('');
    } else {
      this.out.push(INDENT.repeat(this.depth) + text);
    }
  }

  private raw(text: string): void {
    this.out.push(text);
  }

  private indented<T>(fn: () => T): T {
    this.depth++;
    try {
      return fn();
    } finally {
      this.depth--;
    }
  }

  // ── module ──

  emitModule(mod: IRModule): string {
    this.out = [];
    this.depth = 0;
    this.userClassNames = new Set((mod.classes ?? []).map((c) => c.name));

    this.line(`// Transpiled from MQL5 source: ${mod.name}`);
    this.line('// Generated by the mql5-transpiler TypeScript backend.');
    this.line('// Do not edit by hand — regenerate from the .mq5 source.');
    this.line('//');
    this.line('// The module exports a single factory `createExpert(rt, inputs?)`.');
    this.line('// `rt` is the Runtime (../../runtime/runtime.ts); it exposes every');
    this.line('// MQL5 builtin, constant, context var and Standard-Library class.');
    this.line();

    this.line('export function createExpert(rt, inputs = {}) {');
    this.indented(() => {
      // User classes are emitted FIRST, inside the factory, so their methods
      // close over `rt`, the inputs, the globals, and the free user functions
      // (MQL5 methods can call free functions and reference globals directly).
      const classes = mod.classes ?? [];
      this.emitClasses(classes);
      if (classes.length > 0 && (mod.inputs.length > 0 || mod.globals.length > 0 || mod.functions.length > 0)) {
        this.line();
      }

      this.emitInputs(mod.inputs);
      if (mod.inputs.length > 0 && (mod.globals.length > 0 || mod.functions.length > 0)) {
        this.line();
      }

      this.emitGlobals(mod.globals);
      if (mod.globals.length > 0 && mod.functions.length > 0) {
        this.line();
      }

      this.emitFunctions(mod.functions);

      this.line();
      this.emitReturn(mod);
    });
    this.line('}');

    // Single trailing newline.
    return this.out.join('\n') + '\n';
  }

  // ── inputs ──

  /**
   * Each input becomes a `let` so the EA may mutate it, seeded from the
   * `inputs` override map and falling back to the constant-folded default.
   *
   * `inputs.NAME ?? default` (NOT `||`): a default of 0 / false / "" is a VALID
   * input value (global CLAUDE.md §29 — zero is real data). `??` only falls
   * back on null/undefined (the override genuinely absent), never on a falsy
   * supplied value.
   */
  private emitInputs(inputs: IRInput[]): void {
    for (const inp of inputs) {
      const dflt = inp.init !== undefined ? this.expr(inp.init) : this.defaultForType(inp.type);
      const label = inp.label ? `  // ${inp.label}` : '';
      this.line(`let ${inp.name} = (inputs.${inp.name} ?? ${dflt});${label}`);
    }
  }

  // ── globals ──

  private emitGlobals(globals: IRGlobal[]): void {
    for (const g of globals) {
      this.emitGlobal(g);
    }
  }

  private emitGlobal(g: IRGlobal): void {
    // A CTrade-typed global is the Standard-Library trade object: emit it as a
    // constructed singleton `const NAME = new rt.CTrade(rt)` regardless of how
    // the source declared it (MQL5 declares `CTrade trade;` with no `new`).
    if (g.type.named === 'CTrade' && g.init === undefined) {
      this.line(`const ${g.name} = new rt.CTrade(rt);`);
      return;
    }

    const keyword = g.isConst ? 'const' : 'let';

    // Array global with declared dimensions and no initialiser → empty array.
    // (MQL5 dynamic/fixed arrays start empty/zeroed; the runtime's as-series &
    // Copy* builtins populate them. We do not pre-fill — that's runtime work.)
    if (g.arrayDims.length > 0 && g.init === undefined) {
      this.line(`${keyword} ${g.name} = [];`);
      return;
    }

    const init = g.init !== undefined ? this.expr(g.init) : this.defaultForType(g.type);
    this.line(`${keyword} ${g.name} = ${init};`);
  }

  // ── functions ──

  private emitFunctions(functions: IRFunction[]): void {
    for (let i = 0; i < functions.length; i++) {
      if (i > 0) this.line();
      this.emitFunction(functions[i]);
    }
  }

  private emitFunction(fn: IRFunction): void {
    const asyncKw = fn.isAsync ? 'async ' : '';
    const params = fn.params.map((p) => this.param(p)).join(', ');
    this.line(`${asyncKw}function ${fn.name}(${params}) {`);
    this.indented(() => {
      this.emitBlockBody(fn.body);
    });
    this.line('}');
  }

  // ── user classes / structs ──

  private emitClasses(classes: IRClass[]): void {
    for (let i = 0; i < classes.length; i++) {
      if (i > 0) this.line();
      this.emitClass(classes[i]);
    }
  }

  /**
   * Emit a user class/struct as a real TS class:
   *   - fields → class field properties with zero-defaults (or the source init),
   *   - single inheritance → `extends Base`,
   *   - the MQL5 constructor (`ClassName(...)`) → a TS `constructor(...)` that
   *     first chains `super()` when there is a base, then runs the body,
   *   - the destructor (`~ClassName`) → a `__dtor()` method (the runtime's
   *     `delete` hook can invoke it; JS has no destructors),
   *   - every other method → a TS method (async when it transitively trades).
   *
   * Templates are ERASED: `templateParams` is recorded on the IR but the body is
   * emitted un-monomorphised (the type params were untyped during lowering). A
   * note line documents the erasure so the output is self-explaining (§21 —
   * honest about what is and isn't done).
   *
   * KNOWN LIMITATION — NON-VIRTUAL DISPATCH (§21, documented, NOT silently
   * mis-emitted): MQL5/C++ bind a NON-virtual method call statically (to the
   * type of the reference), whereas a TS class method ALWAYS dispatches
   * virtually (to the runtime type). So a non-virtual BASE method that calls an
   * overridden method binds to the BASE implementation in MQL5 but to the
   * DERIVED override here — a behavioural divergence for code that relies on
   * static binding. We emit faithful TS classes (every method virtual) rather
   * than attempting static-binding emulation, which is out of scope. This is
   * surfaced honestly (this comment + `stillUnimplemented`); it is NOT cheaply
   * detectable because the parser does not retain the `virtual`/`override`
   * qualifiers on the AST (see parser.ts parseTypedDecl — virtual/override are
   * consumed but not stored), so we cannot flag the specific divergent call
   * sites without first threading those qualifiers through. EAs that override
   * methods and call them through a non-virtual base method should be reviewed.
   */
  private emitClass(c: IRClass): void {
    if (c.templateParams.length > 0) {
      this.line(
        `// template<${c.templateParams.join(', ')}> — type-erased: emitted ` +
          `un-monomorphised (type params treated as untyped). No specialisation.`,
      );
    }
    const heritage = c.base ? ` extends ${c.base}` : '';
    this.line(`class ${c.name}${heritage} {`);
    this.indented(() => {
      // Fields as class-field properties (run before any constructor body).
      for (const f of c.fields) {
        this.emitField(f);
      }
      if (c.fields.length > 0 && c.methods.length > 0) this.line();

      for (let i = 0; i < c.methods.length; i++) {
        if (i > 0) this.line();
        this.emitMethod(c.methods[i], c);
      }
    });
    this.line('}');
  }

  private emitField(f: IRField): void {
    // Array field with declared dims and no init → empty array (matches the
    // global/local array convention).
    if (f.arrayDims.length > 0 && f.init === undefined) {
      this.line(`${f.name} = [];`);
      return;
    }
    const init = f.init !== undefined ? this.expr(f.init) : this.defaultForType(f.type);
    this.line(`${f.name} = ${init};`);
  }

  private emitMethod(m: IRMethod, c: IRClass): void {
    const params = m.params.map((p) => this.param(p)).join(', ');

    if (m.isCtor) {
      // MQL5 constructor → TS `constructor`. Chain `super()` when there is a
      // base so the derived fields/base ctor run first (TS requires the super
      // call before `this` use in a derived class).
      this.line(`constructor(${params}) {`);
      this.indented(() => {
        if (c.base) this.line('super();');
        this.emitBlockBody(m.body);
      });
      this.line('}');
      return;
    }

    // Destructor → a `__dtor()` method (no params; JS has no destructors). An
    // `async` destructor is unusual but supported for symmetry.
    if (m.isDtor) {
      const asyncKw = m.isAsync ? 'async ' : '';
      this.line(`${asyncKw}__dtor() {`);
      this.indented(() => this.emitBlockBody(m.body));
      this.line('}');
      return;
    }

    const asyncKw = m.isAsync ? 'async ' : '';
    this.line(`${asyncKw}${m.name}(${params}) {`);
    this.indented(() => this.emitBlockBody(m.body));
    this.line('}');
  }

  private param(p: IRParam): string {
    // MQL5 by-ref / array params map to JS reference semantics for objects and
    // arrays directly; defaults are emitted where present.
    if (p.defaultValue !== undefined) {
      return `${p.name} = ${this.expr(p.defaultValue)}`;
    }
    return p.name;
  }

  // ── return object ──

  private emitReturn(mod: IRModule): void {
    const handlerNames: string[] = [];
    for (const name of Object.values(mod.events)) {
      if (name !== undefined && !handlerNames.includes(name)) {
        handlerNames.push(name);
      }
    }

    const inputsObj = mod.inputs.map((i) => i.name).join(', ');

    if (handlerNames.length === 0) {
      this.line(`return { __inputs: { ${inputsObj} } };`);
      return;
    }

    this.line('return {');
    this.indented(() => {
      for (const name of handlerNames) {
        this.line(`${name},`);
      }
      this.line(`__inputs: { ${inputsObj} },`);
    });
    this.line('};');
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Statements
  // ─────────────────────────────────────────────────────────────────────────

  /** Emit the statements of a block WITHOUT its own braces (caller owns them). */
  private emitBlockBody(block: IRBlock): void {
    for (const stmt of block.body) {
      this.stmt(stmt);
    }
  }

  private stmt(s: IRStmt): void {
    switch (s.kind) {
      case 'Block':
        this.line('{');
        this.indented(() => this.emitBlockBody(s));
        this.line('}');
        return;
      case 'VarDecl':
        this.emitVarDecl(s);
        return;
      case 'ExprStmt':
        this.emitExprStmt(s);
        return;
      case 'If':
        this.emitIf(s);
        return;
      case 'For':
        this.emitFor(s);
        return;
      case 'While':
        this.emitWhile(s);
        return;
      case 'DoWhile':
        this.emitDoWhile(s);
        return;
      case 'Return':
        this.emitReturnStmt(s);
        return;
      case 'Break':
        this.line('break;');
        return;
      case 'Continue':
        this.line('continue;');
        return;
      case 'Switch':
        this.emitSwitch(s);
        return;
      default: {
        const _exhaustive: never = s;
        throw new Error(`emit: unhandled statement kind ${JSON.stringify(_exhaustive)}`);
      }
    }
  }

  private emitVarDecl(d: IRVarDecl): void {
    const keyword = d.isConst ? 'const' : 'let';

    // Array local with declared dimensions and no initialiser → empty array.
    if (d.arrayDims.length > 0 && d.init === undefined) {
      this.line(`${keyword} ${d.name} = [];`);
      return;
    }

    const init = d.init !== undefined ? this.expr(d.init) : this.defaultForType(d.type);
    this.line(`${keyword} ${d.name} = ${init};`);
  }

  private emitExprStmt(s: IRExprStmt): void {
    this.line(`${this.expr(s.expr)};`);
  }

  private emitIf(s: IRIf): void {
    this.line(`if (${this.expr(s.cond)}) {`);
    this.indented(() => this.emitStmtAsBlockBody(s.then));

    if (s.else !== undefined) {
      // `else if` chaining: when the else branch is itself an If, keep it on the
      // same `} else if (...)` line for readable, idiomatic output.
      if (s.else.kind === 'If') {
        this.emitElseIf(s.else);
      } else {
        this.line('} else {');
        this.indented(() => this.emitStmtAsBlockBody(s.else as IRStmt));
        this.line('}');
      }
    } else {
      this.line('}');
    }
  }

  private emitElseIf(s: IRIf): void {
    this.line(`} else if (${this.expr(s.cond)}) {`);
    this.indented(() => this.emitStmtAsBlockBody(s.then));

    if (s.else !== undefined) {
      if (s.else.kind === 'If') {
        this.emitElseIf(s.else);
      } else {
        this.line('} else {');
        this.indented(() => this.emitStmtAsBlockBody(s.else as IRStmt));
        this.line('}');
      }
    } else {
      this.line('}');
    }
  }

  /**
   * Emit a statement as the *body* of an enclosing brace block: if it is itself
   * a Block, splice its statements in directly (avoids a redundant nested
   * `{ ... }`); otherwise emit the single statement.
   */
  private emitStmtAsBlockBody(s: IRStmt): void {
    if (s.kind === 'Block') {
      this.emitBlockBody(s);
    } else {
      this.stmt(s);
    }
  }

  private emitFor(s: IRFor): void {
    const init = s.init !== undefined ? this.forInit(s.init) : '';
    const cond = s.cond !== undefined ? this.expr(s.cond) : '';
    const update = s.update !== undefined ? this.expr(s.update) : '';
    this.line(`for (${init}; ${cond}; ${update}) {`);
    this.indented(() => this.emitStmtAsBlockBody(s.body));
    this.line('}');
  }

  /** A `for` init clause — a VarDecl or an ExprStmt — rendered inline (no `;`). */
  private forInit(init: IRVarDecl | IRExprStmt): string {
    if (init.kind === 'VarDecl') {
      const keyword = init.isConst ? 'const' : 'let';
      if (init.arrayDims.length > 0 && init.init === undefined) {
        return `${keyword} ${init.name} = []`;
      }
      const v = init.init !== undefined ? this.expr(init.init) : this.defaultForType(init.type);
      return `${keyword} ${init.name} = ${v}`;
    }
    return this.expr(init.expr);
  }

  private emitWhile(s: IRWhile): void {
    this.line(`while (${this.expr(s.cond)}) {`);
    this.indented(() => this.emitStmtAsBlockBody(s.body));
    this.line('}');
  }

  private emitDoWhile(s: IRDoWhile): void {
    this.line('do {');
    this.indented(() => this.emitStmtAsBlockBody(s.body));
    this.line(`} while (${this.expr(s.cond)});`);
  }

  private emitReturnStmt(s: IRReturn): void {
    if (s.value !== undefined) {
      this.line(`return ${this.expr(s.value)};`);
    } else {
      this.line('return;');
    }
  }

  private emitSwitch(s: IRSwitch): void {
    this.line(`switch (${this.expr(s.disc)}) {`);
    this.indented(() => {
      for (const c of s.cases) {
        if (c.test !== undefined) {
          this.line(`case ${this.expr(c.test)}:`);
        } else {
          this.line('default:');
        }
        this.indented(() => {
          for (const stmt of c.body) {
            this.stmt(stmt);
          }
        });
      }
    });
    this.line('}');
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Expressions
  // ─────────────────────────────────────────────────────────────────────────

  private expr(e: IRExpr): string {
    switch (e.kind) {
      case 'Num':
        return this.num(e);
      case 'Str':
        return this.str(e);
      case 'Bool':
        return (e as IRBool).value ? 'true' : 'false';
      case 'Ref':
        return this.ref(e);
      case 'Member':
        return this.member(e);
      case 'Index':
        return this.index(e);
      case 'Call':
        return this.call(e);
      case 'New':
        return this.newExpr(e);
      case 'Delete':
        return this.deleteExpr(e);
      case 'Unary':
        return this.unary(e);
      case 'Binary':
        return this.binary(e);
      case 'Assign':
        return this.assign(e);
      case 'Ternary':
        return this.ternary(e);
      case 'Cast':
        return this.cast(e);
      default: {
        const _exhaustive: never = e;
        throw new Error(`emit: unhandled expression kind ${JSON.stringify(_exhaustive)}`);
      }
    }
  }

  private num(e: IRNum): string {
    // Distinguish a float-typed literal from an int-typed one so that e.g. a
    // double `0` reads `0` cleanly (JS has one number type; the value is what
    // matters). Non-finite values are emitted as their JS spellings.
    if (!Number.isFinite(e.value)) {
      if (Number.isNaN(e.value)) return 'NaN';
      return e.value > 0 ? 'Infinity' : '-Infinity';
    }
    // Integer value: print without a decimal point. Float value: JS default.
    return String(e.value);
  }

  private str(e: IRStr): string {
    return JSON.stringify(e.value);
  }

  private ref(e: IRRef): string {
    const b = e.binding;
    switch (b.kind) {
      case 'input':
      case 'global':
      case 'local':
      case 'param':
        // Resolved program-level binding → bare identifier.
        return b.name;
      case 'builtinConst':
      case 'contextVar':
        // Compile-time builtin / predefined context var → reached via `rt`.
        // (contextVar names already carry their leading underscore: _Symbol …)
        return `rt.${b.name}`;
      case 'enumMember':
        // Enum member → reached via `rt` (the constants table merges into rt).
        return `rt.${b.name}`;
      case 'thisRef':
        // The `this` receiver inside a user-class method.
        return 'this';
      default: {
        const _exhaustive: never = b;
        throw new Error(`emit: unhandled ref binding ${JSON.stringify(_exhaustive)}`);
      }
    }
  }

  private member(e: IRMember): string {
    return `${this.exprParen(e.object)}.${e.member}`;
  }

  private index(e: IRIndex): string {
    return `${this.exprParen(e.array)}[${this.expr(e.index)}]`;
  }

  private call(e: IRCall): string {
    const args = e.args.map((a) => this.expr(a)).join(', ');
    const awaitKw = e.isAsync ? 'await ' : '';

    switch (e.target.kind) {
      case 'intrinsic':
        // Runtime builtin: rt.NAME(args).
        return `${awaitKw}rt.${e.target.info.name}(${args})`;
      case 'method': {
        // Method call on a receiver: receiver.METHOD(args).
        const recv = this.exprParen(e.target.receiver);
        return `${awaitKw}${recv}.${e.target.method}(${args})`;
      }
      case 'user':
        // User-defined function: NAME(args).
        return `${awaitKw}${e.target.name}(${args})`;
      default: {
        const _exhaustive: never = e.target;
        throw new Error(`emit: unhandled call target ${JSON.stringify(_exhaustive)}`);
      }
    }
  }

  private newExpr(e: IRNew): string {
    const args = e.args.map((a) => this.expr(a));
    // A user-declared class/struct is a top-level decl in the emitted module →
    // construct it BARE (`new Foo(...)`), not through `rt`. (Checked first so a
    // user class never collides with a stdlib name.)
    if (this.userClassNames.has(e.typeName)) {
      return `new ${e.typeName}(${args.join(', ')})`;
    }
    // Standard-Library classes (CTrade, CPositionInfo, CSymbolInfo, CAccountInfo,
    // …) are constructed with `rt` FIRST, then any source-supplied args — their
    // runtime ctors take the Runtime so their accessors reach the broker/feed
    // state. (CTrade, CPositionInfo, CSymbolInfo, CAccountInfo all match this.)
    if (isStdlibClass(e.typeName)) {
      const rest = args.length > 0 ? `, ${args.join(', ')}` : '';
      return `new rt.${e.typeName}(rt${rest})`;
    }
    // Runtime structs (MqlTradeRequest/…) are reached through `rt` by name with
    // NO `rt` arg (a bare value struct, zero-initialised).
    return `new rt.${e.typeName}(${args.join(', ')})`;
  }

  private deleteExpr(e: IRDelete): string {
    // MQL5 `delete obj` frees an object pointer. JS is garbage-collected, so
    // there is no allocation to free; the runtime exposes a no-op hook so the
    // semantics (and any object-side teardown) stay in one place.
    return `rt.__delete(${this.expr(e.operand)})`;
  }

  private unary(e: IRUnary): string {
    const operand = this.exprParen(e.operand);
    switch (e.op) {
      case '*':
        // Pointer dereference. MQL5 object pointers map to JS object references;
        // dereferencing is identity at the value level.
        return operand;
      case '&':
        // Address-of. Likewise identity at the reference level (used for by-ref
        // args, which JS objects/arrays already provide).
        return operand;
      case '++':
      case '--':
        return e.prefix ? `${e.op}${operand}` : `${operand}${e.op}`;
      default:
        // + - ! ~  (all prefix)
        return `${e.op}${operand}`;
    }
  }

  private binary(e: IRBinary): string {
    const left = this.exprParen(e.left);
    const right = this.exprParen(e.right);

    // MQL5 integer division and modulo truncate toward zero. JS `/` is real
    // division and JS `%` already truncates toward zero (it has the sign of the
    // dividend, matching C/MQL5), so:
    //   - integer `/`  → wrap in Math.trunc(a / b) to drop the fractional part.
    //   - integer `%`  → emit `a % b` directly; JS `%` ALREADY matches MQL5's
    //                    truncated-toward-zero remainder for integers, so no
    //                    transform is needed. (Documented per the emission ABI.)
    if (e.intArith && e.op === '/') {
      return `Math.trunc(${this.expr(e.left)} / ${this.expr(e.right)})`;
    }

    return `${left} ${e.op} ${right}`;
  }

  private assign(e: IRAssign): string {
    // Assignment targets are lvalues (refs / members / index) — emit the target
    // un-parenthesised so it stays a valid assignment target.
    const target = this.expr(e.target);
    const value = this.expr(e.value);
    return `${target} ${e.op} ${value}`;
  }

  private ternary(e: IRTernary): string {
    return `${this.exprParen(e.cond)} ? ${this.exprParen(e.then)} : ${this.exprParen(e.else)}`;
  }

  private cast(e: IRCast): string {
    // MQL5 numeric casts to an integer primitive truncate toward zero.
    // Casts to floating / string / bool / named types are value-preserving at
    // the JS level (one number type; explicit String()/Boolean() only where the
    // source kind genuinely differs).
    const inner = e.expr;
    if (this.isIntegerPrim(e.to)) {
      return `Math.trunc(${this.expr(inner)})`;
    }
    if (e.to.prim === 'string') {
      return `String(${this.expr(inner)})`;
    }
    if (e.to.prim === 'bool') {
      return `Boolean(${this.expr(inner)})`;
    }
    // double / float / named / unknown → pass the value through unchanged.
    return this.exprParen(inner);
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Helpers
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * Render `e` parenthesised when it is a compound expression that could bind
   * incorrectly in its surrounding context. Atoms (refs, literals, calls,
   * member/index accesses, `new`) never need parens; everything else gets them.
   * This keeps operator precedence correct without tracking precedence levels.
   */
  private exprParen(e: IRExpr): string {
    if (this.isAtom(e)) {
      return this.expr(e);
    }
    return `(${this.expr(e)})`;
  }

  private isAtom(e: IRExpr): boolean {
    switch (e.kind) {
      case 'Num':
      case 'Str':
      case 'Bool':
      case 'Ref':
      case 'Member':
      case 'Index':
      case 'Call':
      case 'New':
        return true;
      default:
        return false;
    }
  }

  private isIntegerPrim(t: IRType): boolean {
    switch (t.prim) {
      case 'int':
      case 'long':
      case 'uint':
      case 'ulong':
      case 'short':
      case 'ushort':
      case 'char':
      case 'uchar':
      case 'datetime':
      case 'color':
      case 'handle':
        return true;
      default:
        return false;
    }
  }

  /**
   * The default value for a typed declaration with no initialiser, mirroring
   * MQL5's zero-initialisation. A 0 / false / "" default is a real value (§29);
   * it is NOT a stand-in for "absent".
   */
  private defaultForType(t: IRType): string {
    if (t.arrayOf !== undefined) return '[]';
    switch (t.prim) {
      case 'bool':
        return 'false';
      case 'string':
        return '""';
      case 'double':
      case 'float':
      case 'int':
      case 'long':
      case 'uint':
      case 'ulong':
      case 'short':
      case 'ushort':
      case 'char':
      case 'uchar':
      case 'datetime':
      case 'color':
      case 'handle':
        return '0';
      case 'void':
        return 'undefined';
      default:
        // Named / unknown types with no initialiser: null (object pointer) is
        // MQL5's uninitialised object-pointer value.
        return 'null';
    }
  }
}
